### PR TITLE
Gated marketplace/361 funiques errors are not descriptive

### LINKED ISSUE #361: Fruniques errors are not descriptive
**Description**
When a user signs some extrinsic that fails, the error that came out is not descriptive as it only shows `tbac.notAuthorized`, at least it should be more readable as if an user tries to spawn a NFT on a collection where he is not a collaborator the error that should came is `UserIsNotInvitedInCollection`, I'm sure there are more of this errors but let's just focus on this one

### PR DESCRIPTION
**Pull request by Dreyhh**
# Make fruniques errors more descriptive

## Overview

This change improves understanding of failures by making error messages more descriptive.
Err(NotAuthorized) + context --> Err(UserNotInCollection)

Captura de Pantalla 2023-02-13 a la(s) 13 39 16

### Tickets

- [x] Fix #361 

## Implementation notes

It does not change functionality

## Interesting/controversial decisions
We are assuming that if someone does not have Mint permission it means that the user is not in the given collection which could change in the future...an alternative approach is to make the error message "UserDoesNotHaveMintPermission" but that message does not suggest that the solution to the error is to invite the user to the collection.
Also the aim was to address all error messages of the pallet but that one was the only one not descriptive enough already

### CODE REVIEW

**Comment by Dreyhh** [comment]
# Create block_user extrinsic

## Overview

This change introduces a new extrinsic called block_user that allows for the admin of a marketplace to block any user that is not a participant of the marketplace already (whether or not the user has previously applied to the marketplace) such that a blocked user cannot longer join the marketplace without an admin unblocking him first, once a user is blocked all its applications data (if any) related to the marketplace is deleted.
Also, the expiration date for offers has been removed per #87. 

Captura de Pantalla 2023-02-17 a la(s) 11 08 04


### Tickets

- [x] Fix #87 


## Implementation notes

Creates a StorageMap called BlockedUsersByMarketplace.
Creates a function called do_block user to block (add to BlockedUsersByMarketplace) or unblock (remove from BlockedUsersByMarketplace) a user.
Creates is_this_user_blocked helper function to ensure that apply, reapply, invite, and addAuthority extrinsics only works when the user is not blocked.
Creates unit tests for the extrinsic.

## Interesting/controversial decisions
In the scope of the block_user extrinsic, the user is understood to not be a participant of the marketplace already, that is, the block_user extrinsic doesn't work as an "eliminate_participant" extrinsic.

File: pallets/fruniques/src/lib.rs [hunk 1]
```diff
@@ -298,14 +308,19 @@ pub mod pallet {
...
 				);
-
 				ensure!(
 					!<FruniqueInfo<T>>::try_get(parent_info_call.collection_id, parent_info_call.parent_id)
 						.unwrap()
 						.redeemed,
 					Error::<T>::ParentAlreadyRedeemed
 				);
-				Self::is_authorized(user, parent_info_call.collection_id, Permission::Mint)?;
+				ensure!(
```
Comment (didiermis) [inline pallets/fruniques/src/lib.rs:317]: Could you let me know why this second authorization check is required here? Usually, authorization checks are only performed once. If needed, then you could modularize/refactor the functionality.

File: pallets/gated-marketplace/src/functions.rs [hunk 2]
```diff
@@ -830,6 +843,84 @@ impl<T: Config> Pallet<T> {
...
+		authority: T::AccountId,
+		marketplace_id: [u8; 32],
+		user: T::AccountId,
+	) -> DispatchResult {
+		// ensure the marketplace exists
+		ensure!(<Marketplaces<T>>::contains_key(marketplace_id), Error::<T>::MarketplaceNotFound);
+		// ensure the origin is owner or admin
+		Self::is_authorized(authority.clone(), &marketplace_id, Permission::EnlistBlockedUser)?;
+		//ensure the user is not already a participant of the marketplace
+		ensure!(
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs:860]: This validation works, but there are better ways to validate it. I suggest looking into the rbac's storage-maps  or creating a new function if the rbac pallet doesn't expose any public helper function.
Something like:
```rust
fn is_a_market_participant()
```
This actually works because, behind the scenes, the authorization function checks if the role has the selected permission, but here, we would like to know if the user has a specific role in the selected scope. 
See `fn has_role()` from rbac pallet.

File: runtime/src/lib.rs [hunk 3]
```diff
@@ -641,6 +641,7 @@ parameter_types! {
 	pub const MaxAuthsPerMarket:u32 = 3; // 1 of each role (1 owner, 1 admin, etc.)
 	pub const MaxRolesPerAuth: u32 = 2;
 	pub const MaxApplicants: u32 = 10;
+	pub const MaxBlockedUsersPerMarket: u32 = 10;
```
Comment (didiermis) [inline runtime/src/lib.rs]: The current value is low, set a significant number. (1000)

File: pallets/gated-marketplace/src/functions.rs [hunk 4]
```diff
@@ -830,6 +843,84 @@ impl<T: Config> Pallet<T> {
 		Ok(())
 	}
 
+	pub fn do_block_user(
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs:848]: I like the toggle functionality but I'll recommend refactoring the whole function. Let's start using an enum, something like:
```rust
pub enum RedeemArgs<T: Config> {
	AskForRedemption { collection_id: T::CollectionId, item_id: T::ItemId, },
	AcceptRedemption (RedemptionId),
}
```
See gated-marketplace pallet. The above functionality will allow users to select if they want to block/unblock a user in a single extrinsic. 
Then, do a match like:
```rust
			match redeem {
				RedeemArgs::AskForRedemption { collection_id, item_id } => {
					return Self::do_ask_for_redeem(who, marketplace, collection_id, item_id);
				}
				RedeemArgs::AcceptRedemption ( redemption_id ) => {
					return Self::do_accept_redeem(who, marketplace, redemption_id);
				}
			}
```
Then create two separate functions: `do_block_user` & `do_unblock_user`; with the previous modularization, it is easier to read the code.  
You could choose to emit a general event in the primary function `do_block_user` but not in the helper functions or emit an event in each of the following functions: `do_block_user` & `do_unblock_user` but not in the primary function. 

```rust
	UserBlocked(MarketplaceId, T::AccountId),
	/// User was unblocked. [marketplace_id, account]
	UserUnblocked(MarketplaceId, T::AccountId),
```

File: pallets/gated-marketplace/src/functions.rs [hunk 5]
```diff
@@ -830,6 +843,84 @@ impl<T: Config> Pallet<T> {
...
+					// remove application information
+					if let Ok(application) = <Applications<T>>::try_get(application_id){
+						Self::remove_from_applicants_lists(user.clone(), application.status, marketplace_id)?;
+					}
+					<Applications<T>>::remove(application_id);
+					<ApplicationsByAccount<T>>::remove(user.clone(), marketplace_id);
+				}
+			return Ok(());
+		}
+		Self::deposit_event(Event::UserUnblocked(marketplace_id, user));
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs]: Having two events in the same function is kinda weird to read, see my initial comment about this function.

File: pallets/fruniques/src/lib.rs [hunk 6]
```diff
@@ -280,11 +282,19 @@ pub mod pallet {
 			attributes: Option<Attributes<T>>,
 			parent_info_call: Option<ParentInfoCall<T>>,
 		) -> DispatchResult {
+			//Ensure the collection exists
 			ensure!(Self::collection_exists(&class_id), Error::<T>::CollectionNotFound);
+			// Ensure the user is in the collection
 			let user: T::AccountId = ensure_signed(origin.clone())?;
-			Self::is_authorized(user.clone(), class_id, Permission::Mint)?;
+			ensure!(
```
Comment (didiermis) [inline pallets/fruniques/src/lib.rs:289]: Instead of using an ensure with a validation check, I'll suggest using the `has_role`function from the rbac pallet. Let me know if works.

File: pallets/gated-marketplace/src/functions.rs [hunk 7]
```diff
@@ -830,6 +843,84 @@ impl<T: Config> Pallet<T> {
...
+					.iter()
+					.position(|a| *a == user.clone())
+					.ok_or(Error::<T>::UserNotFound)?;
+				blocked_users.remove(user_index);
+				Ok(())
+			},
+		)
+	}
+
+	fn is_user_blocked(
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs]: Depending on the refactor, this function will no longer be needed.

File: pallets/gated-marketplace/src/functions.rs [hunk 8]
```diff
@@ -830,6 +843,84 @@ impl<T: Config> Pallet<T> {
...
+				).is_err(), 
+				Error::<T>::UserAlreadyParticipant
+			);
+		// check if the user is already blocked
+		if Self::try_unblock_user(user.clone(), marketplace_id).is_err() {
+			// if the user is not blocked, block it
+			<BlockedUsersByMarketplace<T>>::try_mutate(marketplace_id, |blocked_list| blocked_list.try_push(user.clone()))
+				.map_err(|_| Error::<T>::ExceedMaxBlockedUsers)?;
+			Self::deposit_event(Event::UserBlocked(marketplace_id, user.clone()));
+			if let Ok(application_id) = <ApplicationsByAccount<T>>::try_get(user.clone(), marketplace_id){
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs]: For now, let's not remove any information from the participant (application, offers, ...). It'll work as a record. We could talk about that after the refactoring.

File: pallets/gated-marketplace/src/lib.rs [hunk 9]
```diff
@@ -187,6 +189,17 @@ pub mod pallet {
 		OptionQuery,
 	>;
 
+	#[pallet::storage]
+	#[pallet::getter(fn get_blocked_accounts)]
+	pub(super) type BlockedUsersByMarketplace<T: Config> = StorageMap<
+		_,
+		Blake2_128Concat,
```
Comment (didiermis) [inline pallets/gated-marketplace/src/lib.rs]: Use identity for the marketpalceid Hasher property

File: pallets/gated-marketplace/src/lib.rs [hunk 10]
```diff
@@ -344,7 +367,23 @@ pub mod pallet {
 			let m = Marketplace { label, fee: Permill::from_percent(fee), creator: who.clone(), };
 			Self::do_create_marketplace(who, admin, m)
 		}
-
+		/// block/unblock a user from apllying to a marketplace.
```
Comment (didiermis) [inline pallets/gated-marketplace/src/lib.rs]: Start with capital letters

**Review by didiermis — CHANGES_REQUESTED** [review]

File: pallets/fruniques/src/lib.rs [hunk 11]
```diff
@@ -280,11 +282,19 @@ pub mod pallet {
 			attributes: Option<Attributes<T>>,
 			parent_info_call: Option<ParentInfoCall<T>>,
 		) -> DispatchResult {
+			//Ensure the collection exists
 			ensure!(Self::collection_exists(&class_id), Error::<T>::CollectionNotFound);
+			// Ensure the user is in the collection
 			let user: T::AccountId = ensure_signed(origin.clone())?;
-			Self::is_authorized(user.clone(), class_id, Permission::Mint)?;
```
Comment (didiermis) [inline pallets/fruniques/src/lib.rs:285]: The initially requested change was because the rbac pallet returns the `NoAuthorized` error,  which makes sense because if the user has not been invited to the collection, then they are not assigned to a role within that scope (collectionID).
The other possible case is when the Fruniques pallet hasn't been initialized. Since the pallet is only initialized once in a lifetime, it is easy to rule out that the error is due to the fact that the pallet was not initialized.
 You could create a new function that checks if the user is part of a collection using the `has_role` function from the rbac. Depending on which order you put all of them together, it will be the error shown in the UI when a non-invited user tries to call the extrinsic. My final thought is: Create a helper function to check if the user is part of the collection.
(DON'T REPLACE THE AUTHORIZATION CHECK, it requires both)
I think @tlacloc could suggest another solution.

**Review by didiermis — CHANGES_REQUESTED** [review]

File: pallets/fruniques/src/lib.rs (hunk 1 above)
Comment (Dreyhh) [reply pallets/fruniques/src/lib.rs:317]: i didn't change the function logic nor its structure but the use case i see for the second validation is to ensure that if the Frunique to spawn has a parent, make sure the user calling spawn has the permission to Mint also in the parent collection.

File: pallets/fruniques/src/lib.rs (hunk 6 above)
Comment (Dreyhh) [reply pallets/fruniques/src/lib.rs:289]: why is _has_role_ a better choice for checking a particular permission? it seems that the only difference is that has_role checks if a user has any of a given set of permissions on the pallet
should i change is_authorized for has_role on the rest of the pallet(s) as well?

File: pallets/gated-marketplace/src/functions.rs (hunk 4 above)
Comment (Dreyhh) [reply pallets/gated-marketplace/src/functions.rs:848]: I like the idea of using an enum to chose whether to block or unblock, and i agree that having two separated helper functions helps by making the code more readable. i will use this approach.

File: pallets/gated-marketplace/src/types.rs [hunk 12]
```diff
@@ -118,6 +126,7 @@ pub enum Permission {
 	TakeBuyOffer,
 	AskForRedemption,
 	AcceptRedemption,
+	EnlistBlockedUser,
```
Comment (didiermis) [inline pallets/gated-marketplace/src/types.rs]: Change permission's name to: BlockUser

File: pallets/gated-marketplace/src/functions.rs [hunk 13]
```diff
@@ -830,6 +845,77 @@ impl<T: Config> Pallet<T> {
...
+					.ok_or(Error::<T>::UserNotFound)?;
+				blocked_list.remove(user_index);
+				Ok(())
+			},
+		)?;
+		Self::deposit_event(Event::UserUnblocked(marketplace_id, user.clone()));
+		Ok(())
+	}
+
+	fn is_user_blocked(user: T::AccountId, marketplace_id: [u8; 32]) -> bool {
```
Comment (didiermis) [inline pallets/gated-marketplace/src/functions.rs:905]: Instead of using all the set of `iter, find, is_some` methods, use a simple `contains`

File: pallets/gated-marketplace/src/lib.rs [hunk 14]
```diff
@@ -88,13 +90,8 @@ pub mod pallet {
...
 	#[pallet::storage]
 	#[pallet::getter(fn applications)]
-	pub(super) type Applications<T: Config> = StorageMap<
-		_,
-		Identity,
-		ApplicationId,
-		Application<T>,
-		OptionQuery,
-	>;
+	pub(super) type Applications<T: Config> =
```
Comment (didiermis) [inline pallets/gated-marketplace/src/lib.rs]: Styles, get back to the old form with the \n: 
`pub(super) type Applications<T: Config> = StorageMap<
		_,

		Identity,

		ApplicationId,

		Application<T>,

		OptionQuery,
	>;
`

File: pallets/gated-marketplace/src/lib.rs [hunk 15]
```diff
@@ -341,10 +362,38 @@ pub mod pallet {
...
+		#[pallet::weight(Weight::from_ref_time(10_000) + T::DbWeight::get().writes(1))]
+		pub fn block_user(
+			origin: OriginFor<T>,
+			marketplace_id: MarketplaceId,
+			block_args: BlockUserArgs<T>,
+		) -> DispatchResult {
+			let who = ensure_signed(origin)?;
+			match block_args {
+				BlockUserArgs::BlockUser(user) => {
+					return Self::do_block_user(who, marketplace_id, user);
```
Comment (didiermis) [inline pallets/gated-marketplace/src/lib.rs]: Remove the return & the semicolon in each matched case, is not necessary since rust knows that if we don't use semicolons, it's a return
`Self::do_block_user(who, marketplace_id, user)`

File: pallets/gated-marketplace/src/tests.rs [hunk 16]
```diff
@@ -2776,3 +2749,294 @@ fn remove_offer_status_is_closed_shouldnt_work() {
 		);
 	});
 }
+
```
Comment (didiermis) [inline pallets/gated-marketplace/src/tests.rs:2758]: Add the `works` or  `should_fail` statement at the end of the tests. 
`block_user_should_prevent_application`  -> `block_user_should_prevent_application_works`

**Review by didiermis — CHANGES_REQUESTED** [review]

File: pallets/gated-marketplace/src/functions.rs (hunk 13 above)
Comment (didiermis) [reply pallets/gated-marketplace/src/functions.rs:905]: `<BlockedUsersByMarketplace<T>>::get(marketplace_id).contains(&user.clone())`

File: pallets/gated-marketplace/src/lib.rs [hunk 17]
```diff
@@ -385,11 +385,9 @@ pub mod pallet {
 		) -> DispatchResult {
 			let who = ensure_signed(origin)?;
 			match block_args {
-				BlockUserArgs::BlockUser(user) => {
-					return Self::do_block_user(who, marketplace_id, user);
-				},
+				BlockUserArgs::BlockUser(user) => Self::do_block_user(who, marketplace_id, user),
```
Comment (didiermis) [inline pallets/gated-marketplace/src/lib.rs]: missing curly brackets here
```rust
			match block_args {
				BlockUserArgs::BlockUser(user) => {
					Self::do_block_user(who, marketplace_id, user)
				},
				BlockUserArgs::UnblockUser(user) => {
					Self::do_unblock_user(who, marketplace_id, user)
				},
			}
```

File: pallets/gated-marketplace/src/tests.rs [hunk 18]
```diff
@@ -2751,7 +2751,7 @@ fn remove_offer_status_is_closed_shouldnt_work() {
 }
 
 #[test]
-fn block_user_should_prevent_application() {
+fn block_user_should_prevent_application_works() {
```
Comment (didiermis) [inline pallets/gated-marketplace/src/tests.rs]: If your unit test proves:
- assert, assert_ok --> works
- assert_noop or any fail --> should_fail

Also missing that statement for some blocking unit tests. Could you add it for all of them?

File: pallets/rbac/src/functions.rs [hunk 19]
```diff
@@ -1,434 +1,514 @@
...
+	}
+
+	/// User any-role validation function
+	///
+	/// Checks if the user has at least one role on the given scope.
+	/// ### Parameters:
+	/// - `user`: The account to validate.
+	/// - `pallet_id`: The unique pallet identifier.
+	/// - `scope_id`: The scope context in which the permission will be validated.
+	fn has_any_role(account: T::AccountId, pallet: IdOrVec, scope_id: &ScopeId) -> bool {
```
Comment (didiermis) [inline pallets/rbac/src/functions.rs]: Due to the needing to "ensure if a user is part of the marketplace," we could use the following code:
```rust 
    fn does_user_have_role_is_this_scope(user: T::AccountId, scope_id: &ScopeId, pallet: IdOrVec) -> bool { 
        let pallet_id = pallet.to_id();
        //option 1
        let rr = UsersByScope::<T>::iter_prefix_values((pallet_id, scope_id)).collect::<Vec<_>>();
        rr.iter().any(|r| r.contains(&user));

        //option 1.1
        let rr2 = UsersByScope::<T>::iter_prefix((pallet_id, scope_id)).collect::<Vec<_>>();
        rr2.iter().any(|r| r.1.contains(&user));

        //option 1.1 compressed
        UsersByScope::<T>::iter_prefix((pallet_id, scope_id)).any(|(role_id, users)| {
            users.contains(&user)
        })
    }
```
Since many roles could be part of a frunique's collection, any of my above options is a better implementation for this problem and future needs. 
Your current implementation could lead to emptiness problems, for example:
When a new entry is created in the RolesByUser storage map, the value of that entry is a vector of roles. But if we remove all the roles from a selected user, the initial entry will still exist with zero values. The contains_key method only checks if the entry exists, and doesn't care about if the value is null or something. 
Use any of my suggested methods and CREATE unit tests for it.

**Review by didiermis — CHANGES_REQUESTED** [review]
Please don't format the whole code while working on a specific task; it's kinda difficult to follow what changes are from the format updating and what part is from the ticket.

File: pallets/gated-marketplace/src/tests.rs [hunk 20]
```diff
@@ -3008,7 +3008,7 @@ fn unblock_user_should_not_work_if_marketplace_does_not_exist() {
 }
 
 #[test]
-fn block_user_should_not_work_if_user_is_already_participant() {
+fn block_user_while_user_is_a_member_of_marketplace_should_fail() {
```
Comment (didiermis) [inline pallets/gated-marketplace/src/tests.rs:2995]: Regarding this test, I wonder why we can't block users from a marketplace if they're already participants.
Blocking should ban a user from a marketplace & prevent future applications. Let's talk about it later.

File: pallets/rbac/src/tests.rs [hunk 21]
```diff
@@ -833,13 +833,26 @@ fn get_role_users_len_should_work() {
 }
 
 #[test]
-fn has_any_role_should_work() {
+fn does_user_have_any_role_in_scope_should_work() {
```
Comment (didiermis) [inline pallets/rbac/src/tests.rs:836]: Can a test be created where a user belongs to multiple scopes? To ensure that the iter_prefix returns a vector of vectors with the primary keys provided.

**Review by didiermis — CHANGES_REQUESTED** [review]
Please remove the `make_free_balance` from the blocking unit tests because it doesn't involve the sell/buy orders of tax credits.

File: pallets/gated-marketplace/src/tests.rs (hunk 20 above)
Comment (Dreyhh) [reply pallets/gated-marketplace/src/tests.rs:2995]: That is what @tlacloc told me the scope of this ticket was. I think it is meant to be a block_user_from_join function...

**Review by didiermis — APPROVED** [review]
LGTM! :+1:

**Review by tlacloc — APPROVED** [review]
LGTM 🚀
